
# Druid\u914D\u7F6E
properties.spring.datasource.druid.stat-view-servlet.login-username=druid
properties.spring.datasource.druid.stat-view-servlet.login-password=druid

# Redis\u914D\u7F6E
spring.data.redis.host=127.0.0.1
spring.data.redis.port=6379
spring.data.redis.database=1
#spring.data.redis.password=1234

# \u5F00\u53D1\u73AF\u5883\u4F7F\u7528\u5185\u5B58\u6570\u636E\u5E93
spring.redis.embedded.enabled=true

# \u6570\u636E\u5E93\u914D\u7F6E
properties.spring.datasource.url=jdbc:mysql://localhost:3306/web_base?useUnicode=true&characterEncoding=utf8&autoReconnect=true&useSSL=true&zeroDateTimeBehavior=convertToNull&serverTimezone=GMT%2b8
properties.spring.datasource.username=root
properties.spring.datasource.password=1234
